### ISSUE TITLE
Sometimes you can see through walls. 

### ISSUE THREAD

**Issue by mogekonik1** [TOHE-AU/TownOfHostEdited#83]
![image](https://user-images.githubusercontent.com/107776037/228907302-f0f6c17b-41f5-42a5-992d-e324295a4603.png)
[TOHE-v2.2.3-2023-03-30_18.46.13.log](https://github.com/KARPED1EM/TownOfHostEdited/files/11114475/TOHE-v2.2.3-2023-03-30_18.46.13.log)

**Comment by mogekonik1** [comment]
Update: After a first meeting effect dissapears

**Comment by KARPED1EM** [comment]
fixed
