### ISSUE TITLE
Kick players under lever doesn't work

### ISSUE THREAD

**Issue by mogekonik1** [TOHE-AU/TownOfHostEdited#92]
![image](https://user-images.githubusercontent.com/107776037/230782267-0fdaed60-cc1c-4d13-8b9f-d8d2a05c9278.png)
![image](https://user-images.githubusercontent.com/107776037/230782275-b5916b98-5e6c-4f50-a89f-d2a2add76b90.png)
[TOHE-v2.2.6-2023-04-09_17.39.12.log](https://github.com/KARPED1EM/TownOfHostEdited/files/11185787/TOHE-v2.2.6-2023-04-09_17.39.12.log)

**Comment by Gurge44** [comment]
It sometimes works for me, but a level 3 player was once in the game while the setting is set to kick players below level 7

**Comment by KARPED1EM** [comment]
fixed
